### ISSUE TITLE
Category and alterations

### ISSUE THREAD

**Issue by souanatx** [daviddmd/assetriskmanager#1]
Hello. I can't create a new type of asset like firewall? Also, after I create an asset I can't change a field like type of asset without having to put a number in the CIA fields.

**Comment by daviddmd** [comment]
@souanatx 

> Hello. I can't create a new type of asset like firewall?

Hello, I've created a fresh Docker environment to test this, and I'm able to create a new asset type (as a Security Officer user). Have you created such an user, or [assigned that role to an user](https://github.com/daviddmd/assetriskmanager/blob/master/documentation/INSTALL.md#resetting-a-users-role)? 

If it isn't related to the currently logged-in user, please provide more information by about the issue by describing the environment where this program is installed, setting  `APP_DEBUG` to true on the .env file and sending details about errors that you may have found.

> Also, after I create an asset I can't change a field like type of asset without having to put a number in the CIA fields.

This is intentional, the form for updating the details of an asset may not be submitted as to unset the values of the CIA fields (whose default values of 0 signify that they are unset).

**Comment by souanatx** [comment]
Solved. Thank you 😊
